import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'ag-grid': 'src/ag-grid.ts',
    datavis: 'src/datavis.ts',
    'hooks/index': 'src/hooks/index.ts',
    'utils/index': 'src/utils/index.ts',
    'tailwind-preset': 'src/tailwind-preset.ts',
    // Individual component entries for tree-shaking
    'components/Alert/index': 'src/components/Alert/index.ts',
    'components/AudioPlayer/index': 'src/components/AudioPlayer/index.ts',
    'components/AudioRecorder/index': 'src/components/AudioRecorder/index.ts',
    'components/Avatar/index': 'src/components/Avatar/index.ts',
    'components/Badge/index': 'src/components/Badge/index.ts',
    'components/Breadcrumb/index': 'src/components/Breadcrumb/index.ts',
    'components/Button/index': 'src/components/Button/index.ts',
    'components/Card/index': 'src/components/Card/index.ts',
    'components/Checkbox/index': 'src/components/Checkbox/index.ts',
    'components/DateInput/index': 'src/components/DateInput/index.ts',
    'components/Dropdown/index': 'src/components/Dropdown/index.ts',
    'components/Input/index': 'src/components/Input/index.ts',
    'components/Modal/index': 'src/components/Modal/index.ts',
    'components/Pagination/index': 'src/components/Pagination/index.ts',
    'components/PhoneInput/index': 'src/components/PhoneInput/index.ts',
    'components/Progress/index': 'src/components/Progress/index.ts',
    'components/QuickAction/index': 'src/components/QuickAction/index.ts',
    'components/Radio/index': 'src/components/Radio/index.ts',
    'components/RecordButton/index': 'src/components/RecordButton/index.ts',
    'components/SchedulePicker/index': 'src/components/SchedulePicker/index.ts',
    'components/Select/index': 'src/components/Select/index.ts',
    'components/Skeleton/index': 'src/components/Skeleton/index.ts',
    'components/Slider/index': 'src/components/Slider/index.ts',
    'components/Spinner/index': 'src/components/Spinner/index.ts',
    'components/Switch/index': 'src/components/Switch/index.ts',
    'components/Table/index': 'src/components/Table/index.ts',
    'components/Tabs/index': 'src/components/Tabs/index.ts',
    'components/Text/index': 'src/components/Text/index.ts',
    'components/Textarea/index': 'src/components/Textarea/index.ts',
    'components/ThemeProvider/index': 'src/components/ThemeProvider/index.ts',
    'components/Tooltip/index': 'src/components/Tooltip/index.ts',
    'components/VisuallyHidden/index': 'src/components/VisuallyHidden/index.ts',
    // Brand system entries for tree-shaking
    'brands/index': 'src/brands/index.ts',
    'brands/types': 'src/brands/types.ts',
    'brands/bluehive': 'src/brands/bluehive.ts',
    'brands/ozwell': 'src/brands/ozwell.ts',
  },
  format: ['esm', 'cjs'],
  target: 'es2022',
  dts: true,
  sourcemap: true,
  clean: true,
  external: ['react', 'react-dom', 'ag-grid-community', 'ag-grid-react', '@mieweb/wcdatavis', 'wcdatavis'],
  treeshake: true,
  splitting: true,
  minify: false,
  esbuildOptions(options) {
    options.jsx = 'automatic';
  },
});
