import type { EmailBlockType, EmailSocialPlatform } from './types';

export const defaultEmailEditorLabels = {
  blocks: 'Blocks',
  design: 'Design',
  blockSettings: 'Block settings',
  undo: 'Undo',
  redo: 'Redo',
  viewport: 'Preview width',
  desktop: 'Desktop',
  mobile: 'Mobile',
  canvas: 'Email canvas',
  moveUp: 'Move up',
  moveDown: 'Move down',
  duplicate: 'Duplicate',
  remove: 'Delete',
  dragHandle: 'Drag to reorder',
  addBlock: 'Add block',
  emptyCanvas: 'Drag a block here, or click one in the palette.',
  emptyColumn: 'Empty column',
  unsupportedBlock:
    'Unsupported block ({type}). It will not be included in the sent email.',
  noSelection: 'Select a block in the canvas to edit it.',
  column: 'Column',
  selectBlock: 'Select {item}',
  announceAdded: '{item} added.',
  announceMoved: '{item} moved to position {position}.',
  announceDuplicated: '{item} duplicated.',
  announceRemoved: '{item} deleted.',
  blockTypes: {
    heading: 'Heading',
    text: 'Text',
    button: 'Button',
    image: 'Image',
    divider: 'Divider',
    spacer: 'Spacer',
    columns: 'Columns',
    social: 'Social links',
    hero: 'Hero banner',
    html: 'Custom HTML',
    footer: 'Footer',
    quote: 'Quote',
    table: 'Table',
  } satisfies Record<EmailBlockType, string>,
  platforms: {
    facebook: 'Facebook',
    twitter: 'Twitter',
    linkedin: 'LinkedIn',
    instagram: 'Instagram',
    youtube: 'YouTube',
    github: 'GitHub',
    website: 'Website',
  } satisfies Record<EmailSocialPlatform, string>,
  fields: {
    text: 'Text',
    content: 'Content',
    level: 'Level',
    alignment: 'Alignment',
    color: 'Color',
    textColor: 'Text color',
    backgroundColor: 'Background color',
    backgroundGradient: 'Background gradient (CSS)',
    accentColor: 'Accent color',
    url: 'Link URL',
    borderRadius: 'Corner radius (px)',
    fullWidth: 'Full width',
    imageUrl: 'Image URL',
    uploadImage: 'Upload image',
    uploadFailed: 'The image could not be uploaded. Try again.',
    altText: 'Alt text',
    width: 'Width (px or %)',
    style: 'Style',
    height: 'Height (px)',
    iconSize: 'Icon size',
    platform: 'Platform',
    socialLink: 'Link {number}',
    addLink: 'Add link',
    removeLink: 'Remove link',
    html: 'HTML',
    companyName: 'Company name',
    address: 'Address',
    phone: 'Phone',
    showUnsubscribe: 'Show unsubscribe link',
    unsubscribeText: 'Unsubscribe text',
    managePreferencesUrl: 'Preferences URL',
    managePreferencesText: 'Preferences text',
    author: 'Author',
    role: 'Role',
    headerRow: 'First row is a header',
    headerBackgroundColor: 'Header background',
    headerTextColor: 'Header text color',
    borderColor: 'Border color',
    addRow: 'Add row',
    addColumn: 'Add column',
    removeRow: 'Remove last row',
    removeColumn: 'Remove last column',
    cell: 'Row {row}, column {column}',
    categoryText: 'Eyebrow',
    headline: 'Headline',
    subtitle: 'Subtitle',
    ctaText: 'Button text',
    ctaUrl: 'Button URL',
    ctaColor: 'Button color',
    padding: 'Vertical padding (px)',
    columnCount: 'Columns',
    bodyBackgroundColor: 'Page background',
    contentBackgroundColor: 'Content background',
    contentWidth: 'Content width (px)',
    fontFamily: 'Font',
    headingColor: 'Heading color',
    linkColor: 'Link color',
    buttonBackgroundColor: 'Button color',
    buttonTextColor: 'Button text color',
    buttonBorderRadius: 'Button corner radius (px)',
  },
  options: {
    left: 'Left',
    center: 'Center',
    right: 'Right',
    solid: 'Solid',
    dashed: 'Dashed',
    dotted: 'Dotted',
    sm: 'Small',
    md: 'Medium',
    lg: 'Large',
  },
};

export type EmailEditorLabels = typeof defaultEmailEditorLabels;

export type EmailEditorLabelOverrides = {
  [K in keyof EmailEditorLabels]?: EmailEditorLabels[K] extends string
    ? string
    : Partial<EmailEditorLabels[K]>;
};

export function mergeEmailEditorLabels(
  overrides: EmailEditorLabelOverrides | undefined
): EmailEditorLabels {
  if (!overrides) return defaultEmailEditorLabels;
  const d = defaultEmailEditorLabels;
  return {
    ...d,
    ...overrides,
    blockTypes: { ...d.blockTypes, ...overrides.blockTypes },
    platforms: { ...d.platforms, ...overrides.platforms },
    fields: { ...d.fields, ...overrides.fields },
    options: { ...d.options, ...overrides.options },
  } as EmailEditorLabels;
}
