export {
  Modal,
  ModalBody,
  type ModalBodyProps,
  ModalClose,
  type ModalCloseProps,
  modalContentVariants,
  ModalFooter,
  type ModalFooterProps,
  ModalHeader,
  type ModalHeaderProps,
  modalOverlayVariants,
  type ModalProps,
  ModalTitle,
  type ModalTitleProps,
} from './Modal';
