export {
  Modal,
  ModalHeader,
  ModalTitle,
  ModalClose,
  ModalBody,
  ModalFooter,
  modalContentVariants,
  modalOverlayVariants,
  type ModalProps,
  type ModalHeaderProps,
  type ModalTitleProps,
  type ModalCloseProps,
  type ModalBodyProps,
  type ModalFooterProps,
} from './Modal';
