export {
  AccessDeniedPage,
  type AccessDeniedPageProps,
  DEFAULT_ERROR_CONFIGS,
  ErrorPage,
  type ErrorPageConfig,
  type ErrorPageProps,
  type ErrorType,
  MaintenancePage,
  type MaintenancePageProps,
  NotFoundPage,
  type NotFoundPageProps,
  OfflinePage,
  type OfflinePageProps,
  ServerErrorPage,
  type ServerErrorPageProps,
} from './ErrorPage';
