export {
  ErrorPage,
  NotFoundPage,
  ServerErrorPage,
  OfflinePage,
  MaintenancePage,
  AccessDeniedPage,
  DEFAULT_ERROR_CONFIGS,
  type ErrorPageProps,
  type NotFoundPageProps,
  type ServerErrorPageProps,
  type OfflinePageProps,
  type MaintenancePageProps,
  type AccessDeniedPageProps,
  type ErrorType,
  type ErrorPageConfig,
} from './ErrorPage';
