/**
 * @mieweb/ui Tailwind CSS Preset
 *
 * This preset provides the default theme configuration for @mieweb/ui components.
 * Consumers can extend or override these values in their own tailwind.config.js
 *
 * Usage:
 * ```js
 * // tailwind.config.js
 * module.exports = {
 *   presets: [require('@mieweb/ui/tailwind-preset')],
 *   theme: {
 *     extend: {
 *       colors: {
 *         primary: {
 *           500: '#your-brand-color',
 *         },
 *       },
 *     },
 *   },
 * };
 * ```
 */

/**
 * Safelist of classes used by @mieweb/ui components.
 *
 * **Tailwind CSS 3**: These must be safelisted because Tailwind may not detect
 * them when components are imported from node_modules.
 *
 * **Tailwind CSS 4**: The safelist is NOT needed if you add the `@source`
 * directive to your CSS. Add this line to your main CSS file:
 *
 *   @source "../node_modules/@mieweb/ui/dist";
 *
 * This tells Tailwind 4 to scan @mieweb/ui's dist folder for class names,
 * replacing the need for a manual safelist.
 *
 * @deprecated For Tailwind CSS 4 users — use the `@source` directive instead.
 */
export const miewebUISafelist = [
  // CaseManagementHeader — logical spacing, details grid, responsive
  // built-in actions (icon-only below md):
  '-ms-2',
  'gap-x-10',
  'hidden',
  'max-w-[60%]',
  'md:hidden',
  'md:inline-flex',
  // PatientHeader showCountBadges={false} — hides CountBadge roots in the
  // actions slot (ui#367):
  '[&_[data-slot=count-badge-root]]:hidden',
  // OzwellChat's compact widget shell and portaled menus. These arbitrary
  // utilities must remain available to Tailwind 3 consumers that do not scan
  // package source files.
  'max-w-[min(142px,38vw)]',
  'max-w-[190px]',
  'max-w-[min(248px,calc(100vw-24px))]',
  'max-w-[min(260px,calc(100vw-24px))]',
  'rounded-[10px]',
  'min-h-[30px]',
  'animate-ozwell-message-flare',
  'grid-cols-[22px_minmax(0,1fr)]',
  'h-[22px]',
  'w-[22px]',
  'text-[11px]',
  'leading-[1.35]',
  'py-[7px]',
  '[&_[data-slot="composer-input"]]:pe-[min(160px,44vw)]',
  '[&_[data-slot="ai-chat"]]:min-h-0',
  '[&_[data-slot="ai-chat-messages"]]:min-h-0',
  '[&_[data-slot="ai-tool-call"]]:p-2',
  '[&_[data-slot="ai-tool-icon"]]:h-7',
  '[&_[data-slot="ai-tool-icon"]]:w-7',
  '[&_[data-slot="ai-tool-content"]]:text-sm',
  '[&_[data-slot="ai-tool-parameters"]]:text-xs',
  '[&_[data-slot="ai-tool-result"]]:text-xs',
  '[&_[data-slot="ai-message-thinking"]_button]:px-2.5',
  '[&_[data-slot="ai-message-thinking"]_button]:py-[7px]',
  '[&_[data-slot="ai-message"].flex-row-reverse_[data-slot="ai-message-avatar"]]:hidden',
  '[&_[data-slot=toast-message]]:text-xs',
  '[&_[data-slot=toast-message]]:leading-[1.35]',
  '[&_[data-slot=toast]]:max-w-none',
  '[&_[data-slot=toast]]:min-w-0',
  '[&_[data-slot=toast]]:rounded-lg',
  '[&_[data-slot=toast]]:p-2',
  '[&_[data-slot=toast]]:shadow-none',
  // Media stack (MediaEditor / TranscriptView / MediaPlayer) — opacity-modifier
  // and state variants introduced with the media components (ui#323 finding):
  'bg-muted/20',
  'bg-primary-50',
  'bg-primary-500/20',
  'bg-primary-500/40',
  'bg-success/15',
  'bg-warning/20',
  'bg-warning/40',
  'border-l-warning',
  'border-primary-600',
  'border-warning/50',
  'dark:bg-primary-950',
  'hover:bg-destructive/20',
  'hover:bg-muted',
  'hover:bg-muted/70',
  'hover:bg-primary-500/15',
  'hover:bg-primary-500/30',
  'hover:bg-success/25',
  'hover:text-destructive',
  // MediaEditor media-surface height cap: the small-screen `dvh` cap, and the
  // md variants that hand desktop back its original percentage cap. Purging
  // these uncaps the player on a phone, which is the bug the cap exists for.
  'max-h-[55dvh]',
  'md:max-h-[50%]',
  'md:max-h-none',
  'outline-destructive',
  'outline-primary-500',
  'outline-warning',
  'text-primary-500',
  // Semantic colors
  'border-border',
  'border-input',
  'ring-ring',
  'bg-background',
  'bg-card',
  'bg-muted',
  'bg-primary',
  'bg-primary-800',
  'dark:bg-primary-500',
  'checked:border-primary-500',
  'dark:checked:border-primary-800',
  'bg-success',
  'bg-warning',
  'bg-destructive',
  'bg-info',
  // Ozwell brand accent (Hey Ozwell voice components)
  'bg-ozwell',
  'hover:bg-ozwell',
  'active:bg-ozwell',
  'text-ozwell',
  'text-ozwell-foreground',
  'border-ozwell',
  'focus-visible:ring-ozwell',
  'text-foreground',
  'text-card-foreground',
  'text-muted-foreground',
  'text-primary',
  'text-primary-foreground',
  'text-success',
  'text-success-foreground',
  'text-warning',
  'text-warning-foreground',
  'text-destructive',
  'text-destructive-foreground',
  'text-info',
  'text-info-foreground',
  'focus:ring-ring',
  'focus:ring-primary',
  'focus:border-transparent',
  'focus:ring-destructive',
  'border-primary',
  'border-destructive',
  'border-success',
  'focus:ring-success/20',
  'focus:ring-destructive/20',
  'opacity-0',
  // Drag & drop (useDragReorder / dragIndicatorClasses)
  'opacity-40',
  'cursor-grab',
  'active:cursor-grabbing',
  'shadow-[inset_0_2px_0_0_var(--color-primary-500,#3b82f6)]',
  'shadow-[inset_0_-2px_0_0_var(--color-primary-500,#3b82f6)]',
  'group-hover:opacity-100',
  'focus:opacity-100',
  'has-[[data-slot=superchat-nitro-table]]:w-full',
  'has-[[data-slot=superchat-nitro-table]]:max-w-full',
  // RowActionToolbar (per-row action toolbars) reveal/overlay. These use the
  // built-in `pointer-fine` variant, named `group/order` scope, and the
  // `.wcdv-tr` (datavis grid row) arbitrary variant — none of which TW3
  // consumers scan from node_modules, so the toolbar would stay hidden
  // without safelisting them.
  'pointer-fine:absolute',
  'pointer-fine:top-1/2',
  'pointer-fine:right-0',
  'pointer-fine:-translate-y-1/2',
  'pointer-fine:top-1.5',
  'pointer-fine:right-1.5',
  'pointer-fine:bg-card',
  'pointer-fine:border-border',
  'pointer-fine:rounded-md',
  'pointer-fine:border',
  'pointer-fine:p-0.5',
  'pointer-fine:shadow-sm',
  'pointer-fine:pointer-events-none',
  'pointer-fine:opacity-0',
  'rounded-md',
  'border',
  'p-0.5',
  'shadow-sm',
  'focus-within:pointer-events-auto',
  'focus-within:opacity-100',
  'group-hover:pointer-events-auto',
  'group-focus-within:pointer-events-auto',
  'group-focus-within:opacity-100',
  'group-focus:pointer-events-auto',
  'group-focus:opacity-100',
  'group-hover/order:pointer-events-auto',
  'group-hover/order:opacity-100',
  'group-focus-within/order:pointer-events-auto',
  'group-focus-within/order:opacity-100',
  'group-focus/order:pointer-events-auto',
  'group-focus/order:opacity-100',
  '[.wcdv-tr:hover_&]:pointer-events-auto',
  '[.wcdv-tr:hover_&]:opacity-100',
  '[.wcdv-tr:focus-within_&]:pointer-events-auto',
  '[.wcdv-tr:focus-within_&]:opacity-100',
  // Markdown SurveyBlock
  'accent-primary-500',
  // Opacity-modifier variants for semantic colors used by components
  'bg-background/60',
  'bg-background/80',
  'bg-background/90',
  'bg-background/95',
  'bg-card/80',
  'bg-destructive/5',
  'bg-destructive/10',
  'bg-foreground/50',
  'bg-info/10',
  'bg-muted/10',
  'bg-muted/30',
  'bg-muted/50',
  'bg-primary/5',
  'bg-primary/10',
  'bg-success/10',
  'bg-warning/10',
  'border-border/80',
  'border-destructive/20',
  'border-destructive/30',
  'border-destructive/50',
  'border-info/30',
  'border-muted-foreground/25',
  'border-muted-foreground/40',
  'border-primary/30',
  'border-primary/50',
  'border-success/30',
  'border-success/50',
  'border-warning/30',
  'hover:bg-destructive/10',
  'hover:bg-muted/10',
  'hover:bg-muted/20',
  'hover:bg-muted/50',
  'hover:bg-muted/80',
  'hover:bg-primary/5',
  'hover:bg-primary/10',
  'hover:bg-primary/20',
  'hover:bg-primary/90',
  'hover:border-border/80',
  'hover:border-muted-foreground/50',
  'hover:text-destructive/80',
  'hover:text-primary/80',
  'text-muted-foreground/30',
  'text-muted-foreground/40',
  'text-muted-foreground/50',
  'text-muted-foreground/60',
  'text-muted-foreground/70',
  'text-primary/80',
  'text-primary-foreground/90',
  'ring-primary',
  'ring-2',
  'ring-offset-2',
  // Grid classes for QuickAction and responsive layouts
  'grid-cols-1',
  'grid-cols-2',
  'grid-cols-3',
  'grid-cols-4',
  'grid-cols-6',
  'sm:grid-cols-1',
  'sm:grid-cols-2',
  'sm:grid-cols-3',
  'sm:grid-cols-4',
  'sm:grid-cols-6',
  'md:grid-cols-2',
  'md:grid-cols-3',
  'md:grid-cols-4',
  'lg:grid-cols-2',
  'lg:grid-cols-3',
  'lg:grid-cols-4',
  // ── Expanded Color Scales ────────────────────────────────────────
  // Secondary scale
  'bg-secondary',
  'bg-secondary-50',
  'bg-secondary-100',
  'bg-secondary-500',
  'bg-secondary-600',
  'text-secondary',
  'text-secondary-500',
  'text-secondary-600',
  'text-secondary-700',
  'text-secondary-foreground',
  'border-secondary',
  'border-secondary-200',
  // Neutral scale
  'bg-neutral-50',
  'bg-neutral-100',
  'bg-neutral-200',
  'bg-neutral-300',
  'bg-neutral-800',
  'bg-neutral-900',
  'text-neutral-500',
  'text-neutral-600',
  'text-neutral-700',
  'text-neutral-400',
  'border-neutral-200',
  'border-neutral-300',
  'dark:bg-neutral-700',
  'dark:bg-neutral-800',
  'dark:text-neutral-300',
  'dark:text-neutral-400',
  'dark:border-neutral-600',
  'dark:border-neutral-700',
  // Indigo (StripeBadge)
  'bg-indigo-500/10',
  'dark:bg-indigo-400/20',
  'text-indigo-700',
  'dark:text-indigo-300',
  'border-indigo-500/30',
  'hover:text-indigo-700',
  'dark:hover:text-indigo-300',
  // Destructive scale
  'bg-destructive-50',
  'bg-destructive-100',
  'bg-destructive-500',
  'bg-destructive-600',
  'bg-destructive-700',
  'hover:bg-destructive-800',
  'text-destructive-500',
  'text-destructive-600',
  'text-destructive-700',
  'text-destructive-800',
  'text-destructive-900',
  'border-destructive-200',
  'border-destructive-300',
  'dark:bg-destructive-900',
  'dark:bg-destructive-950',
  'dark:text-destructive-300',
  'dark:text-destructive-400',
  // Success scale
  'bg-success-50',
  'bg-success-100',
  'bg-success-500',
  'bg-success-600',
  'bg-success-700',
  'hover:bg-success-800',
  'text-success-500',
  'text-success-600',
  'text-success-700',
  'text-success-800',
  'text-success-900',
  'border-success-200',
  'border-success-300',
  'dark:bg-success-900',
  'dark:bg-success-950',
  'dark:text-success-300',
  'dark:text-success-400',
  // Warning scale
  'bg-warning-50',
  'bg-warning-100',
  'bg-warning-500',
  'bg-warning-600',
  'bg-warning-700',
  'text-warning-900',
  'text-warning-500',
  'text-warning-600',
  'text-warning-700',
  'text-warning-800',
  'text-warning-900',
  'border-warning-200',
  'border-warning-300',
  'dark:bg-warning-900',
  'dark:bg-warning-950',
  'dark:text-warning-300',
  'dark:text-warning-400',
  // Info scale
  'bg-info-50',
  'bg-info-100',
  'bg-info-500',
  'bg-info-600',
  'text-info-500',
  'text-info-600',
  'text-info-700',
  'text-info-800',
  'text-info-900',
  'border-info-200',
  'border-info-300',
  'dark:bg-info-900',
  'dark:bg-info-950',
  'dark:text-info-300',
  'dark:text-info-400',
  // Chart colors
  'bg-chart-1',
  'bg-chart-2',
  'bg-chart-3',
  'bg-chart-4',
  'bg-chart-5',
  'text-chart-1',
  'text-chart-2',
  'text-chart-3',
  'text-chart-4',
  'text-chart-5',
  'border-chart-1',
  'border-chart-2',
  'border-chart-3',
  'border-chart-4',
  'border-chart-5',
  // Switch component
  'bg-primary-500',
  // Primary scale (a11y contrast)
  'text-primary-800',
  'dark:text-primary-300',
  // Text decoration
  'underline',
  'h-5',
  'w-9',
  'h-6',
  'w-11',
  'h-7',
  'w-14',
  'h-4',
  'w-4',
  'w-5',
  'w-6',
  'translate-x-0.5',
  'translate-x-4',
  'translate-x-5',
  'translate-x-7',
  // RTL primitives batch: Badge/Input/Label icon+required markers, Text
  // logical alignment, Switch thumb travel (LTR data-state pairs + rtl mirror)
  'me-1',
  'ms-0.5',
  'ms-1',
  'text-start',
  'text-end',
  'data-[state=checked]:translate-x-4',
  'data-[state=checked]:translate-x-5',
  'data-[state=checked]:translate-x-7',
  'rtl:-translate-x-0.5',
  'rtl:data-[state=checked]:-translate-x-4',
  'rtl:data-[state=checked]:-translate-x-5',
  'rtl:data-[state=checked]:-translate-x-7',
  // RTL layout+nav batch: AppHeader alignment, Card accent/badge positions,
  // Sheet sides, Sidebar off-canvas + paddings, Table cell alignment
  'me-auto',
  'ms-auto',
  '-end-1',
  'start-0',
  'end-0',
  'ps-4',
  'start-2',
  'end-2',
  'border-e',
  'border-s',
  'me-3',
  'ms-2',
  'ps-2',
  '-me-2',
  '-end-3',
  'start-3',
  'pe-4',
  'ps-10',
  'rtl:translate-x-full',
  'translate-x-0',
  '-translate-x-full',
  '[&:has([role=checkbox])]:pe-0',
  // SchedulePicker / overflow handling
  'overflow-x-auto',
  'overflow-hidden',
  // Scrollable floating panels (DateInput calendar, Autocomplete, Select, Table, ScrollArea, …)
  'overflow-auto',
  // Select component
  'truncate',
  // AIReconciliationPanel
  'ring-primary-200',
  'dark:ring-primary-900',
  'border-primary-300',
  'dark:border-primary-700',
  'bg-primary-50/60',
  'dark:bg-primary-950/30',
  'text-primary-700',
  'dark:text-primary-400',
  'border-border/60',
  'bg-muted/40',
  'bg-muted/60',
  'divide-border',
  'max-h-[60vh]',
  'bg-success-100',
  'dark:bg-success-900/30',
  'bg-amber-100',
  'bg-amber-200',
  'text-amber-700',
  'text-amber-800',
  'text-amber-200',
  'text-amber-300',
  'dark:bg-amber-900/30',
  'dark:bg-amber-900/40',
  'dark:text-amber-200',
  'dark:text-amber-300',
  'ring-1',
  'last:border-b-0',
  'border-dashed',
  'text-[11px]',
  // CodeLookup memory picklist (frequently-used pick count)
  'text-primary-600',
  // CodeLookup coding-system toggle (segmented radiogroup pills)
  'flex',
  'flex-wrap',
  'items-center',
  'gap-1',
  'rounded-full',
  'px-2.5',
  'py-0.5',
  'text-xs',
  'transition-colors',
  'focus:ring-2',
  'focus:outline-none',
  'border-primary-800',
  'dark:border-primary-400',
  'dark:bg-primary-400',
  'dark:text-primary-950',
  'text-white',
  'hover:text-foreground',
  // CollabStatus debug panel (fixed-width portal, definition grid, log grid)
  'w-[26rem]',
  'max-w-[calc(100vw-1rem)]',
  'grid-cols-[auto_1fr]',
  'grid-cols-[auto_auto_1fr]',
  // SuperChat (participant chips, unread badge, active/hover states)
  'bg-primary-100',
  'bg-primary-600',
  'hover:bg-primary-700',
  'dark:bg-primary-900/40',
  'text-primary-900',
  'dark:text-primary-100',
  'dark:text-primary-200',
  'hover:border-primary-300',
  'focus:border-primary-500',
  'focus:ring-primary-500',
  'text-[10px]',
  // SuperChat mermaid diagram wrapper — arbitrary variants applied to the
  // injected <svg> so the diagram sizes naturally instead of collapsing.
  '[&_svg]:h-auto',
  '[&_svg]:max-w-none',
  // AI pills — CollapsiblePill / MCPToolCall arbitrary utilities
  'rounded-[8px]',
  'rounded-[10px]',
  'px-[11px]',
  'max-h-0',
  'max-h-[500px]',
  'transition-[max-height,opacity]',
  'overflow-y-auto',
  'focus-visible:ring-ring',
  'focus-visible:ring-offset-1',
  // ThinkingBlock (violet reasoning pill)
  'bg-violet-50',
  'bg-violet-500',
  'border-violet-200',
  'text-violet-600',
  'hover:bg-violet-100',
  'focus-visible:ring-violet-500',
  'animate-pulse',
  'text-[13px]',
  'dark:bg-violet-400',
  'dark:bg-violet-950/30',
  'dark:border-violet-700',
  'dark:border-violet-800',
  'dark:hover:bg-violet-950/50',
  'dark:text-violet-400',
  // MCPToolCall status pills (green success / red error kept the same)
  'bg-green-50',
  'border-green-200',
  'text-green-700',
  'dark:bg-green-900/20',
  'dark:border-green-800',
  'dark:text-green-300',
  'bg-red-50',
  'border-red-200',
  'text-red-700',
  'dark:bg-red-900/20',
  'dark:border-red-800',
  'dark:text-red-300',
  'bg-neutral-100',
  'border-neutral-200',
  'text-neutral-600',
  'text-neutral-400',
  'dark:bg-neutral-800',
  'dark:border-neutral-700',
  'dark:text-neutral-400',
  'bg-primary-50',
  'border-primary-200',
  'text-primary-800',
  'dark:bg-primary-900/20',
  'dark:border-primary-800',
  'dark:text-primary-300',
  'opacity-60',
  // CustomizableDashboard — responsive column grid, flattened columns,
  // drag handle, drop placeholder
  'grid-cols-1',
  'md:grid-cols-2',
  'lg:grid-cols-3',
  'max-lg:contents',
  'max-md:hidden',
  'min-h-16',
  'min-h-32',
  'cursor-grab',
  'active:cursor-grabbing',
  'touch-none',
  'opacity-40',
  'group-hover/portlet:opacity-100',
  'focus-visible:opacity-100',
  '[@media(hover:none)]:opacity-100',
  'group/portlet',
  '[&>:nth-child(2)]:ms-auto',
  'flex-nowrap',
  'bg-card/80',
  'border-dashed',
  'border-2',
  'bg-primary-500/10',
  'gap-0.5',
  'p-0.5',
  // Floating labels (labelVariant="floating" on Input / Textarea / DateInput /
  // Select, ui#406). The peer-* float states, arbitrary font size, and the
  // taller field heights/paddings never appear in consumer markup, so TW3
  // would purge them. (The bare `peer` marker class generates no CSS and
  // needs no safelisting.)
  'placeholder:text-transparent',
  'relative',
  'h-11',
  'h-14',
  'h-16',
  'pt-4',
  'pt-5',
  'pt-6',
  'pt-7',
  'pb-1',
  'pb-1.5',
  'pb-2',
  'min-h-[76px]',
  'min-h-[96px]',
  'min-h-[120px]',
  // Floating-group field boxes (labelVariant="floating" on RadioGroup /
  // CheckboxGroup) share the floating input heights as min-heights. sr-only
  // visually hides the group legend (and the hideLabel input label) while
  // keeping it accessible. mb-1.5 spaces stacked legends (legends ignore
  // fieldset flex gap) and mt-1 spaces floating-group descriptions.
  'min-h-11',
  'min-h-14',
  'min-h-16',
  'sr-only',
  'mb-1.5',
  'mt-1',
  'absolute',
  'pointer-events-none',
  'select-none',
  'transition-all',
  'duration-200',
  'ease-out',
  'top-0.5',
  'top-1',
  'top-1.5',
  'top-2',
  'top-3',
  'top-4',
  'top-5',
  'top-1/2',
  '-translate-y-1/2',
  'translate-y-0',
  'text-sm',
  'text-base',
  'text-lg',
  'text-[0.65rem]',
  'peer-focus:top-0.5',
  'peer-focus:top-1',
  'peer-focus:top-1.5',
  'peer-focus:top-2',
  'peer-focus:text-[0.65rem]',
  'peer-focus:text-xs',
  'peer-focus:text-sm',
  'peer-focus:translate-y-0',
  'peer-[:not(:placeholder-shown)]:top-0.5',
  'peer-[:not(:placeholder-shown)]:top-1',
  'peer-[:not(:placeholder-shown)]:top-1.5',
  'peer-[:not(:placeholder-shown)]:top-2',
  'peer-[:not(:placeholder-shown)]:text-[0.65rem]',
  'peer-[:not(:placeholder-shown)]:text-xs',
  'peer-[:not(:placeholder-shown)]:text-sm',
  'peer-[:not(:placeholder-shown)]:translate-y-0',
  'peer-autofill:top-0.5',
  'peer-autofill:top-1',
  'peer-autofill:top-1.5',
  'peer-autofill:top-2',
  'peer-autofill:text-[0.65rem]',
  'peer-autofill:text-xs',
  'peer-autofill:text-sm',
  'peer-autofill:translate-y-0',
  // DockablePanel — full-screen dialog that collapses to a bottom-right dock:
  // scrim, dock geometry, panel chrome, clipped full-width content
  'fixed',
  'inset-0',
  'inset-6',
  'inset-auto',
  'bg-slate-900/45',
  'end-0',
  'end-6',
  'bottom-0',
  'top-full',
  'w-full',
  'h-full',
  'w-[26rem]',
  'max-w-[calc(100vw-3rem)]',
  'max-w-[90rem]',
  'w-[min(90rem,100vw-3rem)]',
  'h-[calc(100vh-4rem)]',
  'max-sm:inset-0',
  'max-sm:inset-x-0',
  'max-sm:w-full',
  'max-sm:w-screen',
  'max-sm:max-w-full',
  'shadow-[0_1.25rem_2.5rem_rgb(15_23_42/0.22)]',
  'rounded-lg',
  'rounded-t-lg',
  'border',
  'border-b',
  'border-b-0',
  'flex',
  'flex-1',
  'flex-col',
  'relative',
  'absolute',
  'items-center',
  'justify-center',
  'justify-between',
  'gap-1',
  'gap-2',
  'px-3',
  'py-2.5',
  'm-0',
  'min-h-0',
  'min-w-0',
  'text-sm',
  'text-[0.9375rem]',
  'font-semibold',
  'capitalize',
  'sr-only',
];

export interface MiewebUIPreset {
  darkMode: ['class', '[data-theme="dark"]'];
  safelist: string[];
  theme: {
    extend: Record<string, unknown>;
  };
}

export const miewebUIPreset: MiewebUIPreset = {
  darkMode: ['class', '[data-theme="dark"]'],
  safelist: miewebUISafelist,
  theme: {
    extend: {
      colors: {
        // Primary color scale - easily overridable by consumers
        primary: {
          DEFAULT: 'var(--mieweb-primary, var(--mieweb-primary-500, #27aae1))',
          50: 'var(--mieweb-primary-50, #e6f7fc)',
          100: 'var(--mieweb-primary-100, #b3e6f6)',
          200: 'var(--mieweb-primary-200, #80d5f0)',
          300: 'var(--mieweb-primary-300, #4dc4ea)',
          400: 'var(--mieweb-primary-400, #27aae1)',
          500: 'var(--mieweb-primary-500, #27aae1)',
          600: 'var(--mieweb-primary-600, #1f98ca)',
          700: 'var(--mieweb-primary-700, #1786b3)',
          800: 'var(--mieweb-primary-800, #0f749c)',
          900: 'var(--mieweb-primary-900, #086285)',
          950: 'var(--mieweb-primary-950, #00506e)',
          foreground: 'var(--mieweb-primary-foreground, hsl(210 40% 98%))',
        },
        // Ozwell brand accent (the "Hey Ozwell" octopus blue) — distinct from the host app primary.
        ozwell: {
          DEFAULT: 'var(--mieweb-ozwell, #0BA0E0)',
          foreground: 'var(--mieweb-ozwell-foreground, hsl(0 0% 100%))',
        },
        // Secondary color scale
        secondary: {
          DEFAULT: 'var(--mieweb-secondary-500, #6366f1)',
          50: 'var(--mieweb-secondary-50, #eef2ff)',
          100: 'var(--mieweb-secondary-100, #e0e7ff)',
          200: 'var(--mieweb-secondary-200, #c7d2fe)',
          300: 'var(--mieweb-secondary-300, #a5b4fc)',
          400: 'var(--mieweb-secondary-400, #818cf8)',
          500: 'var(--mieweb-secondary-500, #6366f1)',
          600: 'var(--mieweb-secondary-600, #4f46e5)',
          700: 'var(--mieweb-secondary-700, #4338ca)',
          800: 'var(--mieweb-secondary-800, #3730a3)',
          900: 'var(--mieweb-secondary-900, #312e81)',
          950: 'var(--mieweb-secondary-950, #1e1b4b)',
          foreground: 'var(--mieweb-secondary-foreground, #ffffff)',
        },
        // Neutral / gray scale
        neutral: {
          DEFAULT: 'var(--mieweb-neutral-500, #737373)',
          50: 'var(--mieweb-neutral-50, #fafafa)',
          100: 'var(--mieweb-neutral-100, #f5f5f5)',
          200: 'var(--mieweb-neutral-200, #e5e5e5)',
          300: 'var(--mieweb-neutral-300, #d4d4d4)',
          400: 'var(--mieweb-neutral-400, #a3a3a3)',
          500: 'var(--mieweb-neutral-500, #737373)',
          600: 'var(--mieweb-neutral-600, #525252)',
          700: 'var(--mieweb-neutral-700, #404040)',
          800: 'var(--mieweb-neutral-800, #262626)',
          900: 'var(--mieweb-neutral-900, #171717)',
          950: 'var(--mieweb-neutral-950, #0a0a0a)',
        },
        // Semantic colors using CSS variables for theming
        border: 'var(--mieweb-border, hsl(214.3 31.8% 91.4%))',
        input: 'var(--mieweb-input, hsl(214.3 31.8% 91.4%))',
        ring: 'var(--mieweb-ring, hsl(221.2 83.2% 53.3%))',
        background: 'var(--mieweb-background, hsl(0 0% 100%))',
        foreground: 'var(--mieweb-foreground, hsl(222.2 84% 4.9%))',
        // Component-specific semantic colors
        card: {
          DEFAULT: 'var(--mieweb-card, hsl(0 0% 100%))',
          foreground: 'var(--mieweb-card-foreground, hsl(222.2 84% 4.9%))',
        },
        muted: {
          DEFAULT: 'var(--mieweb-muted, hsl(210 40% 96.1%))',
          foreground: 'var(--mieweb-muted-foreground, hsl(215.4 16.3% 46.9%))',
        },
        // Destructive / error scale
        destructive: {
          DEFAULT:
            'var(--mieweb-destructive, var(--mieweb-destructive-500, #dc2626))',
          50: 'var(--mieweb-destructive-50, #fef2f2)',
          100: 'var(--mieweb-destructive-100, #fee2e2)',
          200: 'var(--mieweb-destructive-200, #fecaca)',
          300: 'var(--mieweb-destructive-300, #fca5a5)',
          400: 'var(--mieweb-destructive-400, #f87171)',
          500: 'var(--mieweb-destructive-500, #dc2626)',
          600: 'var(--mieweb-destructive-600, #dc2626)',
          700: 'var(--mieweb-destructive-700, #b91c1c)',
          800: 'var(--mieweb-destructive-800, #991b1b)',
          900: 'var(--mieweb-destructive-900, #7f1d1d)',
          950: 'var(--mieweb-destructive-950, #450a0a)',
          foreground: 'var(--mieweb-destructive-foreground, hsl(210 40% 98%))',
        },
        // Success scale
        success: {
          DEFAULT: 'var(--mieweb-success-500, #22c55e)',
          50: 'var(--mieweb-success-50, #f0fdf4)',
          100: 'var(--mieweb-success-100, #dcfce7)',
          200: 'var(--mieweb-success-200, #bbf7d0)',
          300: 'var(--mieweb-success-300, #86efac)',
          400: 'var(--mieweb-success-400, #4ade80)',
          500: 'var(--mieweb-success-500, #22c55e)',
          600: 'var(--mieweb-success-600, #16a34a)',
          700: 'var(--mieweb-success-700, #15803d)',
          800: 'var(--mieweb-success-800, #166534)',
          900: 'var(--mieweb-success-900, #14532d)',
          950: 'var(--mieweb-success-950, #052e16)',
          foreground: 'var(--mieweb-success-foreground, hsl(355.7 100% 97.3%))',
        },
        // Warning scale
        warning: {
          DEFAULT: 'var(--mieweb-warning-500, #f59e0b)',
          50: 'var(--mieweb-warning-50, #fffbeb)',
          100: 'var(--mieweb-warning-100, #fef3c7)',
          200: 'var(--mieweb-warning-200, #fde68a)',
          300: 'var(--mieweb-warning-300, #fcd34d)',
          400: 'var(--mieweb-warning-400, #fbbf24)',
          500: 'var(--mieweb-warning-500, #f59e0b)',
          600: 'var(--mieweb-warning-600, #d97706)',
          700: 'var(--mieweb-warning-700, #b45309)',
          800: 'var(--mieweb-warning-800, #92400e)',
          900: 'var(--mieweb-warning-900, #78350f)',
          950: 'var(--mieweb-warning-950, #451a03)',
          foreground: 'var(--mieweb-warning-foreground, hsl(26 83.3% 14.1%))',
        },
        // Info scale
        info: {
          DEFAULT: 'var(--mieweb-info-500, #0ea5e9)',
          50: 'var(--mieweb-info-50, #f0f9ff)',
          100: 'var(--mieweb-info-100, #e0f2fe)',
          200: 'var(--mieweb-info-200, #bae6fd)',
          300: 'var(--mieweb-info-300, #7dd3fc)',
          400: 'var(--mieweb-info-400, #38bdf8)',
          500: 'var(--mieweb-info-500, #0ea5e9)',
          600: 'var(--mieweb-info-600, #0284c7)',
          700: 'var(--mieweb-info-700, #0369a1)',
          800: 'var(--mieweb-info-800, #075985)',
          900: 'var(--mieweb-info-900, #0c4a6e)',
          950: 'var(--mieweb-info-950, #082f49)',
          foreground: 'var(--mieweb-info-foreground, #ffffff)',
        },
        // Chart / data visualization
        chart: {
          1: 'var(--mieweb-chart-1, #27aae1)',
          2: 'var(--mieweb-chart-2, #22c55e)',
          3: 'var(--mieweb-chart-3, #f59e0b)',
          4: 'var(--mieweb-chart-4, #ef4444)',
          5: 'var(--mieweb-chart-5, #6366f1)',
        },
      },
      fontFamily: {
        sans: [
          'var(--mieweb-font-sans, ui-sans-serif)',
          'system-ui',
          'sans-serif',
        ],
      },
      borderRadius: {
        '2xl': 'var(--mieweb-radius-2xl, 1rem)',
        lg: 'var(--mieweb-radius-lg, 0.75rem)',
        md: 'var(--mieweb-radius-md, 0.5rem)',
        sm: 'var(--mieweb-radius-sm, 0.25rem)',
        xl: 'var(--mieweb-radius-xl, 1rem)',
      },
      boxShadow: {
        card: 'var(--mieweb-shadow-card, 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1))',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'slide-in-from-top': {
          '0%': { transform: 'translateY(-0.5rem)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-in-from-bottom': {
          '0%': { transform: 'translateY(0.5rem)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-in-right': {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'slide-in-left': {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'ozwell-message-flare': {
          '0%': {
            boxShadow:
              '0 0 0 0 color-mix(in srgb, var(--mieweb-primary-700, #1786b3) 34%, transparent)',
          },
          '70%': {
            boxShadow:
              '0 0 0 8px color-mix(in srgb, var(--mieweb-primary-700, #1786b3) 0%, transparent)',
          },
          '100%': {
            boxShadow:
              '0 0 0 0 color-mix(in srgb, var(--mieweb-primary-700, #1786b3) 0%, transparent)',
          },
        },
      },
      animation: {
        'fade-in': 'fade-in 150ms ease-out',
        'fade-out': 'fade-out 150ms ease-in',
        'slide-in-from-top': 'slide-in-from-top 150ms ease-out',
        'slide-in-from-bottom': 'slide-in-from-bottom 150ms ease-out',
        'slide-in-right': 'slide-in-right 300ms ease-out',
        'slide-in-left': 'slide-in-left 300ms ease-out',
        'scale-in': 'scale-in 150ms ease-out',
        'ozwell-message-flare': 'ozwell-message-flare 1.8s ease-out',
      },
    },
  },
};

export default miewebUIPreset;
