/**
 * @mieweb/ui Tailwind CSS Preset (CommonJS)
 *
 * This file is used during build time by tailwind.config.js
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', '[data-theme="dark"]'],
  // Safelist classes used by @mieweb/ui components that may not be detected
  // when components are imported from node_modules (especially with Tailwind CSS 4)
  safelist: [
    // CaseManagementHeader — logical spacing, details grid, responsive
    // built-in actions (icon-only below md):
    '-ms-2',
    'gap-x-10',
    'hidden',
    'max-w-[60%]',
    'md:hidden',
    'md:inline-flex',
    // OzwellChatView — model selector width cap in ChatComposer's selector row
    'max-w-[min(160px,44vw)]',
    // Semantic colors
    'border-border',
    'border-input',
    'ring-ring',
    'bg-background',
    'bg-card',
    'bg-muted',
    'bg-destructive',
    'text-foreground',
    'text-card-foreground',
    'text-muted-foreground',
    'text-destructive',
    'text-destructive-foreground',
    'focus:ring-ring',
    'focus:border-transparent',
    'focus:ring-destructive',
    'border-destructive',
    // Grid classes for QuickAction and responsive layouts
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'grid-cols-6',
    'sm:grid-cols-1',
    'sm:grid-cols-2',
    'sm:grid-cols-3',
    'sm:grid-cols-4',
    'sm:grid-cols-6',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:grid-cols-4',
    'lg:grid-cols-2',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    // Switch component
    'bg-neutral-200',
    'dark:bg-neutral-700',
    'bg-primary-500',
    // BusinessHoursEditor rules-variant day chips
    'border-primary-800',
    'bg-primary-800',
    'text-white',
    'h-5',
    'w-9',
    'h-6',
    'w-11',
    'h-7',
    'w-14',
    'h-4',
    'w-4',
    'w-5',
    'w-6',
    'translate-x-0.5',
    'translate-x-4',
    'translate-x-5',
    'translate-x-7',
    // RTL primitives batch: Badge/Input/Label icon+required markers, Text
    // logical alignment, Switch thumb travel (LTR data-state pairs + rtl mirror)
    'me-1',
    'ms-0.5',
    'ms-1',
    'text-start',
    'text-end',
    'data-[state=checked]:translate-x-4',
    'data-[state=checked]:translate-x-5',
    'data-[state=checked]:translate-x-7',
    'rtl:-translate-x-0.5',
    'rtl:data-[state=checked]:-translate-x-4',
    'rtl:data-[state=checked]:-translate-x-5',
    'rtl:data-[state=checked]:-translate-x-7',
    // RTL layout+nav batch: AppHeader alignment, Card accent/badge positions,
    // Sheet sides, Sidebar off-canvas + paddings, Table cell alignment
    'me-auto',
    'ms-auto',
    '-end-1',
    'start-0',
    'end-0',
    'ps-4',
    'start-2',
    'end-2',
    'border-e',
    'border-s',
    'me-3',
    'ms-2',
    'ps-2',
    '-me-2',
    '-end-3',
    'start-3',
    'pe-4',
    'ps-10',
    'rtl:translate-x-full',
    'translate-x-0',
    '-translate-x-full',
    '[&:has([role=checkbox])]:pe-0',
    // RTL messaging+AI batch: bubble tails, composer borders/paddings, corner
    // pins (AIChatModal/AttachmentPicker/MessageList), read-receipt avatar stack
    'end-1',
    'end-3',
    'end-4',
    'start-4',
    'me-2',
    'pe-10',
    'border-s-4',
    'rounded-ee-md',
    'rounded-es-md',
    'rtl:space-x-reverse',
    // RTL DocScanner+media batch: detection-overlay corner pins, MediaEditor
    // speed-marker accent/pill, ScriptPanel border, transcript alignment
    '-end-0.5',
    '-start-0.5',
    '-start-1',
    'end-0.5',
    'rounded-ee',
    'rounded-ee-lg',
    'rounded-es',
    'rounded-es-lg',
    'rounded-se',
    'rounded-se-lg',
    'rounded-ss',
    'rounded-ss-lg',
    'border-e-4',
    'border-s-[3px]',
    'border-s-warning',
    'border-s-primary-500',
    'ps-1.5',
    '-start-px',
    'md:border-e',
    // RTL billing+invoices batch: invoice tables/headers, search icon inset,
    // button spinners
    '-ms-1',
    'ps-9',
    'sm:text-end',
    // RTL services+employer batch: wizard steps, accordion insets, provider
    // selectors, service cards/badges
    'border-s-0',
    'border-s-2',
    'ms-1.5',
    'ms-3',
    'ms-4',
    'ms-6',
    'pe-3',
    'pe-8',
    'pe-16',
    'ps-0',
    'ps-3',
    'ps-7',
    'ps-8',
    'rounded-s-md',
    'rounded-e-md',
    'bg-right',
    'rtl:bg-left',
    // RTL scheduling+clinical batch: calendar insets, timeline dots, order forms
    '-start-5',
    'border-e-0',
    'md:border-s',
    'ms-2.5',
    'pe-2',
    'ps-1',
    'ps-6',
    'rounded-s-none',
    'start-1',
    'first:border-s-0',
    'rtl:origin-right',
    // RTL Phase 2: Toast slide-in animation + RTL mirror
    'animate-slide-in-right',
    'rtl:animate-slide-in-left',
    // RTL Phase 2: directional icon mirroring (chevrons/arrows)
    'rtl:-scale-x-100',
    // RTL shell/misc batch: command palette, site chrome, superchat, toolbars
    'end-12',
    'md:end-4',
    'md:start-auto',
    'md:text-start',
    'me-1.5',
    'pe-12',
    'pointer-fine:end-0',
    'pointer-fine:end-1.5',
    'ps-11',
    'ps-12',
    'rounded-e-lg',
    'rounded-s-lg',
    'sm:text-start',
    'start-5',
    // MediaEditor media-surface height cap: the small-screen `dvh` cap, and the
    // md variants that hand desktop back its original percentage cap. Purging
    // these uncaps the player on a phone, which is the bug the cap exists for.
    'max-h-[55dvh]',
    'md:max-h-[50%]',
    'md:max-h-none',
    // SchedulePicker / overflow handling
    'overflow-x-auto',
    'overflow-hidden',
    // Scrollable floating panels (DateInput calendar, Autocomplete, Select, Table, ScrollArea, …)
    'overflow-auto',
    // Select component
    'truncate',
    // Kbd / KeyboardShortcutsOverlay — key chips and shortcut rows
    'px-1.5',
    'font-mono',
    'mx-0.5',
    'list-none',
    // FilterSummaryBar — filtered-grid summary bar and clear action
    'border-primary-300',
    'dark:border-primary-700',
    'bg-muted/60',
    'dark:text-primary-200',
    'rounded-md',
    'py-1',
    'text-primary-700',
    'hover:bg-primary-500/15',
    'dark:text-primary-300',
    'dark:hover:text-primary-200',
    'h-2.5',
    'w-2.5',
    'focus-visible:ring-offset-2',
    // Sparkline — bar sizing, gaps, and hover tints
    'min-w-[3px]',
    'gap-[2px]',
    'bg-primary-500/40',
    'hover:bg-primary-500/70',
    'hover:bg-primary-500/90',
    'hover:bg-muted-foreground/20',
    'focus-visible:ring-offset-1',
    'items-end',
    'w-16',
    'pb-0.5',
    'leading-tight',
    'tracking-wider',
    'rounded-sm',
    'cursor-pointer',
    // ClampedText — collapsed clamp levels and fade gradient
    'line-clamp-2',
    'line-clamp-3',
    'line-clamp-4',
    'line-clamp-5',
    'line-clamp-6',
    'line-clamp-7',
    'line-clamp-8',
    'bg-gradient-to-t',
    'from-card',
    'from-background',
    'to-transparent',
    'break-words',
    'whitespace-pre-wrap',
    'mt-1',
    'hover:underline',
    // FreshnessBadge / FreshnessDot — tinted level chips and dots
    'bg-success/10',
    'dark:bg-success/20',
    'bg-warning/15',
    'dark:bg-warning/20',
    'text-warning-700',
    'dark:text-warning',
    'bg-destructive/10',
    'dark:bg-destructive/20',
    'bg-muted-foreground/50',
    'h-2',
    'w-2',
    'inline-block',
    'bg-success',
    'bg-warning',
    'text-success',
    'text-success-800',
    'text-warning-800',
    'text-destructive-700',
    'dark:text-success',
    'dark:text-destructive',
    // Accordion — grid-rows height animation (arbitrary values TW3 won't scan)
    'transition-[grid-template-rows]',
    'grid-rows-[0fr]',
    'grid-rows-[1fr]',
    'disabled:opacity-50',
    'disabled:pointer-events-none',
    'divide-border',
    'divide-y',
    'duration-200',
    'ease-out',
    'first:rounded-t-lg',
    'focus-visible:outline-none',
    'focus-visible:ring-inset',
    'gap-3',
    'grid',
    'hover:bg-muted/60',
    'last:rounded-b-lg',
    'pb-4',
    'px-5',
    'py-4',
    'rotate-180',
    'transition-transform',
    // GlossaryTooltip hover card — trigger reset, gradient header, chips, footer links
    '[font:inherit]',
    'appearance-none',
    'bg-muted/50',
    'bg-transparent',
    'bg-white/15',
    'block',
    'border-0',
    'border-t',
    'dark:hover:text-primary-400',
    'flex-wrap',
    'font-bold',
    'font-medium',
    'font-normal',
    'gap-1.5',
    'h-3',
    'hover:border-primary-400',
    'hover:text-primary-700',
    'hover:text-primary-800',
    'inline',
    'inline-flex',
    'items-start',
    'leading-relaxed',
    'leading-snug',
    'mb-1',
    'mb-1.5',
    'mt-2',
    'normal-case',
    'outline-none',
    'p-0',
    'px-2',
    'text-inherit',
    'text-primary-500',
    'text-primary-800',
    'text-white/70',
    'text-xs',
    'tracking-normal',
    'w-3',
    'z-50',

    // SourceTip hover card — trigger affordance, gradient header, ring, scroll cap
    'cursor-help',
    'underline',
    'text-primary-600',
    'hover:text-primary-500',
    'dark:text-primary-400',
    'dark:hover:text-primary-300',
    'text-muted-foreground/70',
    'w-80',
    'decoration-dashed',
    'decoration-primary-400/70',
    'bg-primary-400',
    'underline-offset-4',
    'bg-gradient-to-br',
    'from-primary-700',
    'to-primary-600',
    'ring-black/5',
    'dark:ring-white/10',
    'ring-1',
    'overflow-y-auto',
    'focus-visible:ring-2',
    'focus-visible:ring-ring',
    'max-h-52',
    'text-primary-100/90',
    'text-[10px]',
    // SuperChat message actions (footer bar + sticky overflow menu) — arbitrary
    // touch-pointer variants and stacking above rich content (z-50 internals),
    // plus the standard utilities of the sticky wrapper and its footer handoff
    // (`invisible` keeps the hidden trigger out of the tab order).
    '[@media(pointer:coarse)]:opacity-100',
    'z-[60]',
    'z-10',
    'invisible',
    'transition-opacity',
    'bottom-2',
    'mt-auto',
    // Dropdown submenu flyout — preferred width clamped to the viewport.
    'min-w-[min(10rem,calc(100vw-1rem))]',
    'text-[11px]',
    'text-[13px]',
    'px-3.5',
    'py-2.5',
    'mt-2.5',
    'pt-2.5',
    'mt-0.5',
    'mt-1.5',
    'h-1.5',
    'w-1.5',
    'border-dashed',
    'shadow-xl',
    // CopyButton — inline copy-to-clipboard button
    'p-1',
    'hover:bg-muted',

    // ReadingProgressBar — fixed top rail and width-transition fill
    'pointer-events-none',
    'inset-x-0',
    'h-1',
    'transition-[width]',
    'duration-150',

    // Sidebar — desktop collapse animates the inline size only
    'transition-[width,min-width]',

    // SectionSpyNav — sticky rail, brand tone whites, sliding underline
    'sticky',
    'top-0',
    'z-30',
    'bg-primary-900',
    'bg-card/95',
    'backdrop-blur',
    'gap-4',
    'px-4',
    'py-0.5',
    'shrink-0',
    'tracking-wide',
    'uppercase',
    'text-white/85',
    '[scrollbar-width:none]',
    '[&::-webkit-scrollbar]:hidden',
    'rounded',
    'px-2.5',
    'py-2',
    'whitespace-nowrap',
    // Button label keeps child SVGs in inline flow (preflight makes SVGs
    // block-level, which would force line breaks inside the label span).
    '[&_svg]:inline-block',
    '[&_svg]:align-middle',
    // Button `effect` variants (sheen/orbit) lift the button on hover; the
    // mie-fx-* classes themselves are plain CSS in styles/effects.css.
    'hover:-translate-y-0.5',
    // VideoCard hover-preview progress bar rounds its leading-fill edge.
    'rounded-e-full',
    'transition-colors',
    'hover:text-white',
    'hover:text-foreground',
    'h-0.5',
    'rounded-full',
    'transition-[left,width]',
    'duration-300',
    'hover:bg-white/10',
    'h-3.5',
    'w-3.5',
    // CustomizableDashboard — responsive column grid, flattened columns,
    // drag handle, drop placeholder
    'grid-cols-1',
    'md:grid-cols-2',
    'lg:grid-cols-3',
    'max-lg:contents',
    'max-md:hidden',
    'min-h-16',
    'min-h-32',
    'cursor-grab',
    'active:cursor-grabbing',
    'touch-none',
    'opacity-40',
    'group-hover/portlet:opacity-100',
    'focus-visible:opacity-100',
    '[@media(hover:none)]:opacity-100',
    'group/portlet',
    '[&>:nth-child(2)]:ms-auto',
    'flex-nowrap',
    'bg-card/80',
    'border-dashed',
    'border-2',
    'bg-primary-500/10',
    // Modules/Views — accentClasses resolves an Accent token name to a wash, a
    // border and a solid marker, so none of them appear literally in a
    // consumer's own source. The wash and marker classes are listed elsewhere
    // in this file; these borders and the neutral marker are not.
    'border-primary-500/40',
    'border-success/40',
    'border-warning/40',
    'border-destructive/40',
    'border-info/40',
    'bg-muted-foreground',
    'gap-0.5',
    'p-0.5',
    // DockablePanel — full-screen dialog that collapses to a bottom-right dock:
    // scrim, dock geometry, panel chrome, clipped full-width content
    'fixed',
    'inset-0',
    'inset-6',
    'inset-auto',
    'bg-slate-900/45',
    'end-0',
    'end-6',
    'bottom-0',
    'top-full',
    'w-full',
    'h-full',
    'w-[26rem]',
    'max-w-[calc(100vw-3rem)]',
    'max-w-[90rem]',
    'w-[min(90rem,100vw-3rem)]',
    'h-[calc(100vh-4rem)]',
    'max-sm:inset-0',
    'max-sm:inset-x-0',
    'max-sm:w-full',
    'max-sm:w-screen',
    'max-sm:max-w-full',
    'shadow-[0_1.25rem_2.5rem_rgb(15_23_42/0.22)]',
    'rounded-lg',
    'rounded-t-lg',
    'border',
    'border-b',
    'border-b-0',
    'flex',
    'flex-1',
    'flex-col',
    'relative',
    'absolute',
    'items-center',
    'justify-center',
    'justify-between',
    'gap-1',
    'gap-2',
    'px-3',
    'py-2.5',
    'm-0',
    'min-h-0',
    'min-w-0',
    'text-sm',
    'text-[0.9375rem]',
    'font-semibold',
    'capitalize',
    'sr-only',
    // ChatComposer responsive grid: stacked cells below md, single-row pill
    // (md: overrides) above, plus the card surface
    'grid-cols-[auto_minmax(0,1fr)_auto]',
    'col-span-3',
    'col-start-1',
    'col-start-3',
    'row-start-1',
    'row-start-2',
    'px-1',
    'pt-1',
    'pt-2',
    'pb-1',
    'rounded-2xl',
    'dark:bg-[#1c1c1e]',
    'dark:border-[#2e2e30]',
    'md:col-span-1',
    'md:col-start-2',
    'md:row-start-1',
    'md:self-end',
    'md:p-1.5',
    'md:py-1.5',
    'md:px-0',
    'md:pe-0.5',
    'md:ps-0.5',
    'md:gap-0.5',
    // EH frontdoor ports (ui#420) — arbitrary values, opacity modifiers, and
    // variants emitted by MegaMenu / VideoCard / YearTimeline / SliderCalculator /
    // OrbitRing / RadialExplorer / Globe that TW3 consumers can't generate.
    // Shared positioning & typography
    '-translate-x-1/2',
    '-translate-y-1/2',
    'left-1/2',
    'top-1/2',
    'tabular-nums',
    'aspect-square',
    'aspect-video',
    'backdrop-blur-md',
    // SiteHeader mobile drawer — static group labels reuse the link style
    'hover:bg-transparent',
    'pb-2',
    // MegaMenu — panel layout, feature column gradient, link states
    '[&_svg]:h-4',
    '[&_svg]:h-5',
    '[&_svg]:h-7',
    '[&_svg]:w-4',
    '[&_svg]:w-5',
    '[&_svg]:w-7',
    '[background:linear-gradient(160deg,color-mix(in_srgb,var(--mieweb-accent,var(--mieweb-primary-700))_70%,#000)_0%,var(--mieweb-primary-950)_100%)]',
    'grid-cols-[1fr_280px]',
    'w-[min(600px,calc(100vw-2rem))]',
    'w-[min(880px,calc(100vw-2rem))]',
    'transition-[opacity,transform]',
    'motion-safe:animate-[mie-fade-in_0.2s_ease-out]',
    'bg-white/10',
    'border-white/40',
    'text-foreground/70',
    'text-foreground/80',
    'text-white/80',
    'text-white/90',
    'hover:bg-primary-500/10',
    'hover:bg-primary-900',
    'hover:border-primary-500',
    'hover:border-white',
    'group-hover:bg-primary-800',
    'group-hover:text-primary-800',
    'group-hover:text-white',
    'dark:group-hover:text-primary-200',
    'focus-visible:bg-primary-500/10',
    // VideoCard — hover-preview conic progress ring and play button
    '[-webkit-mask:radial-gradient(farthest-side,transparent_calc(100%-4px),#000_calc(100%-4px))]',
    '[mask:radial-gradient(farthest-side,transparent_calc(100%-4px),#000_calc(100%-4px))]',
    '[background:conic-gradient(from_0deg,transparent_0deg,var(--mieweb-primary-500)_90deg,var(--mieweb-primary-300)_240deg,var(--mieweb-primary-200)_320deg,transparent_360deg)]',
    'drop-shadow-[0_0_5px_color-mix(in_srgb,var(--mieweb-primary-400)_60%,transparent)]',
    'bg-white/90',
    'group-hover:opacity-100',
    'group-hover:scale-110',
    'group-focus-visible:opacity-100',
    'motion-safe:animate-[mie-spin_1.4s_linear_infinite]',
    // YearTimeline — spine gradient, markers, responsive label rail
    'grid-cols-12',
    'md:grid',
    'md:grid-cols-[var(--yt-label)_1fr]',
    'md:block',
    'md:inline',
    'md:pb-4',
    'md:py-3.5',
    'md:h-[22px]',
    'md:border-border/60',
    'before:absolute',
    'before:content-[""]',
    'before:inset-x-0',
    'before:top-0',
    'before:left-1/2',
    'before:-translate-x-1/2',
    'before:h-1',
    'before:h-2.5',
    'before:w-2.5',
    'before:rounded-full',
    'before:bg-primary-700',
    'before:z-[4]',
    'before:[background:linear-gradient(90deg,var(--mieweb-accent,var(--mieweb-primary-400))_0%,var(--mieweb-primary-500)_50%,var(--mieweb-success)_80%,var(--mieweb-accent,var(--mieweb-primary-400))_100%)]',
    '[background:linear-gradient(180deg,var(--mieweb-primary-700),color-mix(in_srgb,var(--mieweb-primary-700)_15%,transparent))]',
    '[&_svg]:h-3.5',
    '[&_svg]:w-3.5',
    '[text-shadow:0_1px_1px_rgba(0,0,0,0.3)]',
    'bg-muted/30',
    'border-border/60',
    'hover:bg-muted/40',
    'text-[9px]',
    'tracking-[0.08em]',
    'tracking-[0.09em]',
    'tracking-[0.11em]',
    'tracking-[0.12em]',
    'z-[1]',
    'z-[3]',
    'z-[5]',
    // SliderCalculator — dark panel gradients and glassy rows
    '[background:linear-gradient(90deg,var(--mieweb-accent,var(--mieweb-primary-300)),var(--mieweb-primary-300))]',
    '[background:radial-gradient(120%_120%_at_100%_0%,var(--mieweb-primary-800),var(--mieweb-primary-950)_70%)]',
    'lg:grid-cols-[1.1fr_1fr]',
    'sm:p-8',
    'sm:text-3xl',
    'sm:text-6xl',
    'bg-white/5',
    'border-white/10',
    'border-white/15',
    'text-white/60',
    'text-white/75',
    'last:border-0',
    // OrbitRing — attract-loop rotation, pause-on-hover, glow ring
    'group/orbit',
    'group/sat',
    '[container-type:size]',
    'motion-safe:animate-[mie-spin_var(--dur)_linear_infinite]',
    'group-hover/orbit:[animation-play-state:paused]',
    'group-focus-within/orbit:[animation-play-state:paused]',
    '[background:radial-gradient(circle_at_50%_38%,#fff_0%,color-mix(in_srgb,var(--mieweb-accent,var(--mieweb-primary-200))_14%,#fff)_52%,color-mix(in_srgb,var(--mieweb-accent,var(--mieweb-primary-200))_30%,#fff)_100%)]',
    '[background:radial-gradient(closest-side,color-mix(in_srgb,var(--mieweb-accent,var(--mieweb-primary-300))_30%,transparent)_0%,color-mix(in_srgb,var(--mieweb-accent,var(--mieweb-primary-300))_12%,transparent)_42%,transparent_78%)]',
    'shadow-[0_0_0_1px_color-mix(in_srgb,var(--mieweb-accent,var(--mieweb-primary-400))_35%,transparent),0_10px_30px_rgba(0,0,0,0.18),0_0_46px_color-mix(in_srgb,var(--mieweb-accent,var(--mieweb-primary-400))_42%,transparent)]',
    'dark:border-primary-800',
    // RadialExplorer — dot navigation and reveal animation
    'motion-safe:animate-[mie-fade-in_0.25s_ease-out]',
    'text-[15px]',
    'tracking-[0.14em]',
    // Globe — HTML overlay chrome (TW3 consumers using the /globe entry)
    'bg-[var(--mieweb-accent,#ffe7b0)]',
    'shadow-[0_0_8px_var(--mieweb-accent,#ffe7b0)]',
    'bg-neutral-950/70',
    'max-w-[min(90%,360px)]',
    'motion-safe:animate-[mie-fade-in_0.28s_ease]',
    // RadialExplorer / VideoCard / SliderCalculator stragglers
    'tracking-[0.18em]',
    'tracking-tight',
    'start-1/2',
    'w-[calc(var(--re-r)*2+120px)]',
    'bg-[linear-gradient(90deg,var(--mieweb-primary-500),var(--mieweb-primary-300))]',
    'bg-black/55',
    'bg-black/60',
    'group-hover:text-primary-700',
    'dark:group-hover:text-primary-300',
    // SiteHeader — menus/MegaMenuBar row and mobile drawer (touched in ui#420)
    'bg-black/50',
    'bg-white/20',
    'bg-white/80',
    'border-white/30',
    'hover:bg-white/90',
    'hover:bg-gray-100',
    'hover:bg-red-50',
    'hover:text-gray-700',
    'hover:text-gray-900',
    'max-h-[calc(100dvh-10rem)]',
    'md:flex',
    'sm:block',
    'dark:border-b',
    'dark:bg-gray-800',
    'dark:bg-gray-900',
    'dark:bg-gray-900/80',
    'dark:bg-primary-900/30',
    'dark:border-gray-600',
    'dark:border-gray-700',
    'dark:border-gray-800',
    'dark:hover:bg-gray-700',
    'dark:hover:bg-gray-800',
    'dark:hover:bg-red-900/20',
    'dark:hover:text-gray-200',
    'dark:hover:text-white',
    'dark:text-gray-300',
    'dark:text-red-400',
    'dark:text-white',
    // Badge usages added in ui#420 (VideoCard duration pill, RadialExplorer tag)
    'dark:bg-black/60',
    'bg-primary-100',
    'text-primary-900',
    'dark:bg-primary-900',
    'dark:text-primary-100',
    // Motion preset safelist: fallback animations and runtime-selected scale origins
    'animate-fade-in',
    'origin-top',
    'origin-bottom',
    'origin-left',
    'origin-right',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'var(--mieweb-primary-50, #f0f9ff)',
          100: 'var(--mieweb-primary-100, #e0f4fe)',
          200: 'var(--mieweb-primary-200, #b9eafd)',
          300: 'var(--mieweb-primary-300, #7cdbfc)',
          400: 'var(--mieweb-primary-400, #36c9f8)',
          500: 'var(--mieweb-primary-500, #27aae1)',
          600: 'var(--mieweb-primary-600, #0c90c9)',
          700: 'var(--mieweb-primary-700, #0b73a3)',
          800: 'var(--mieweb-primary-800, #0f6086)',
          900: 'var(--mieweb-primary-900, #124f6f)',
          950: 'var(--mieweb-primary-950, #0c334a)',
        },
        // Ozwell brand accent (the "Hey Ozwell" octopus blue) — a sub-brand color distinct from the host
        // app's primary. Themeable via --mieweb-ozwell; falls back to the octopus blue.
        ozwell: {
          DEFAULT: 'var(--mieweb-ozwell, #0BA0E0)',
          foreground: 'var(--mieweb-ozwell-foreground, hsl(0 0% 100%))',
        },
        border: 'var(--mieweb-border, hsl(214.3 31.8% 91.4%))',
        input: 'var(--mieweb-input, hsl(214.3 31.8% 91.4%))',
        ring: 'var(--mieweb-ring, hsl(221.2 83.2% 53.3%))',
        background: 'var(--mieweb-background, hsl(0 0% 100%))',
        foreground: 'var(--mieweb-foreground, hsl(222.2 84% 4.9%))',
        card: {
          DEFAULT: 'var(--mieweb-card, hsl(0 0% 100%))',
          foreground: 'var(--mieweb-card-foreground, hsl(222.2 84% 4.9%))',
        },
        muted: {
          DEFAULT: 'var(--mieweb-muted, hsl(210 40% 96.1%))',
          foreground: 'var(--mieweb-muted-foreground, hsl(215.4 16.3% 46.9%))',
        },
        destructive: {
          DEFAULT:
            'var(--mieweb-destructive, var(--mieweb-destructive-500, hsl(0 72.2% 50.6%)))',
          foreground: 'var(--mieweb-destructive-foreground, hsl(210 40% 98%))',
        },
        success: {
          DEFAULT: 'var(--mieweb-success, hsl(142.1 76.2% 36.3%))',
          foreground: 'var(--mieweb-success-foreground, hsl(355.7 100% 97.3%))',
        },
        warning: {
          DEFAULT: 'var(--mieweb-warning, hsl(45.4 93.4% 47.5%))',
          foreground: 'var(--mieweb-warning-foreground, hsl(26 83.3% 14.1%))',
        },
      },
      fontFamily: {
        sans: [
          'var(--mieweb-font-sans, ui-sans-serif)',
          'system-ui',
          'sans-serif',
        ],
      },
      borderRadius: {
        lg: 'var(--mieweb-radius-lg, 0.75rem)',
        md: 'var(--mieweb-radius-md, 0.5rem)',
        sm: 'var(--mieweb-radius-sm, 0.25rem)',
        xl: 'var(--mieweb-radius-xl, 1rem)',
      },
      boxShadow: {
        card: 'var(--mieweb-shadow-card, 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1))',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'slide-in-from-top': {
          '0%': { transform: 'translateY(-0.5rem)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-in-from-bottom': {
          '0%': { transform: 'translateY(0.5rem)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'ozwell-message-flare': {
          '0%': {
            boxShadow:
              '0 0 0 0 color-mix(in srgb, var(--mieweb-primary-700, #0b73a3) 34%, transparent)',
          },
          '70%': {
            boxShadow:
              '0 0 0 8px color-mix(in srgb, var(--mieweb-primary-700, #0b73a3) 0%, transparent)',
          },
          '100%': {
            boxShadow:
              '0 0 0 0 color-mix(in srgb, var(--mieweb-primary-700, #0b73a3) 0%, transparent)',
          },
        },
      },
      animation: {
        'fade-in': 'fade-in 150ms ease-out',
        'fade-out': 'fade-out 150ms ease-in',
        'slide-in-from-top': 'slide-in-from-top 150ms ease-out',
        'slide-in-from-bottom': 'slide-in-from-bottom 150ms ease-out',
        'scale-in': 'scale-in 150ms ease-out',
        'ozwell-message-flare': 'ozwell-message-flare 1.8s ease-out',
      },
      // ClampedText supports 7/8-line clamps beyond Tailwind 3's core 1–6 scale
      lineClamp: {
        7: '7',
        8: '8',
      },
    },
  },
};
