/**
 * @mieweb/ui Tailwind CSS Preset
 *
 * This preset provides the default theme configuration for @mieweb/ui components.
 * Consumers can extend or override these values in their own tailwind.config.js
 *
 * Usage:
 * ```js
 * // tailwind.config.js
 * module.exports = {
 *   presets: [require('@mieweb/ui/tailwind-preset')],
 *   theme: {
 *     extend: {
 *       colors: {
 *         primary: {
 *           500: '#your-brand-color',
 *         },
 *       },
 *     },
 *   },
 * };
 * ```
 */

/**
 * Safelist of classes used by @mieweb/ui components.
 * These must be safelisted because Tailwind may not detect them when
 * components are imported from node_modules (especially with Tailwind CSS 4).
 */
export const miewebUISafelist = [
  // Semantic colors
  'border-border',
  'border-input',
  'ring-ring',
  'bg-background',
  'bg-card',
  'bg-muted',
  'bg-primary',
  'bg-success',
  'bg-warning',
  'bg-destructive',
  'bg-info',
  'text-foreground',
  'text-card-foreground',
  'text-muted-foreground',
  'text-primary',
  'text-primary-foreground',
  'text-success',
  'text-success-foreground',
  'text-warning',
  'text-warning-foreground',
  'text-destructive',
  'text-destructive-foreground',
  'text-info',
  'text-info-foreground',
  'focus:ring-ring',
  'focus:ring-primary',
  'focus:border-transparent',
  'focus:ring-destructive',
  'border-primary',
  'border-destructive',
  'border-success',
  'focus:ring-success/20',
  'focus:ring-destructive/20',
  // Opacity-modifier variants for semantic colors used by components
  'bg-background/60',
  'bg-background/80',
  'bg-background/90',
  'bg-background/95',
  'bg-card/80',
  'bg-destructive/5',
  'bg-destructive/10',
  'bg-foreground/50',
  'bg-info/10',
  'bg-muted/10',
  'bg-muted/30',
  'bg-muted/50',
  'bg-primary/5',
  'bg-primary/10',
  'bg-success/10',
  'bg-warning/10',
  'border-border/80',
  'border-destructive/20',
  'border-destructive/30',
  'border-destructive/50',
  'border-info/30',
  'border-muted-foreground/25',
  'border-muted-foreground/40',
  'border-primary/30',
  'border-primary/50',
  'border-success/30',
  'border-success/50',
  'border-warning/30',
  'hover:bg-destructive/10',
  'hover:bg-muted/10',
  'hover:bg-muted/20',
  'hover:bg-muted/50',
  'hover:bg-muted/80',
  'hover:bg-primary/5',
  'hover:bg-primary/10',
  'hover:bg-primary/20',
  'hover:bg-primary/90',
  'hover:border-border/80',
  'hover:border-muted-foreground/50',
  'hover:text-destructive/80',
  'hover:text-primary/80',
  'text-muted-foreground/30',
  'text-muted-foreground/40',
  'text-muted-foreground/50',
  'text-muted-foreground/60',
  'text-muted-foreground/70',
  'text-primary/80',
  'text-primary-foreground/90',
  'ring-primary',
  'ring-2',
  'ring-offset-2',
  // Grid classes for QuickAction and responsive layouts
  'grid-cols-1',
  'grid-cols-2',
  'grid-cols-3',
  'grid-cols-4',
  'grid-cols-6',
  'sm:grid-cols-1',
  'sm:grid-cols-2',
  'sm:grid-cols-3',
  'sm:grid-cols-4',
  'sm:grid-cols-6',
  'md:grid-cols-2',
  'md:grid-cols-3',
  'md:grid-cols-4',
  'lg:grid-cols-2',
  'lg:grid-cols-3',
  'lg:grid-cols-4',
  // ── Expanded Color Scales ────────────────────────────────────────
  // Secondary scale
  'bg-secondary',
  'bg-secondary-50',
  'bg-secondary-100',
  'bg-secondary-500',
  'bg-secondary-600',
  'text-secondary',
  'text-secondary-500',
  'text-secondary-600',
  'text-secondary-700',
  'text-secondary-foreground',
  'border-secondary',
  'border-secondary-200',
  // Neutral scale
  'bg-neutral-50',
  'bg-neutral-100',
  'bg-neutral-200',
  'bg-neutral-300',
  'bg-neutral-800',
  'bg-neutral-900',
  'text-neutral-500',
  'text-neutral-600',
  'text-neutral-700',
  'text-neutral-400',
  'border-neutral-200',
  'border-neutral-300',
  'dark:bg-neutral-700',
  'dark:bg-neutral-800',
  'dark:text-neutral-300',
  'dark:text-neutral-400',
  'dark:border-neutral-600',
  'dark:border-neutral-700',
  // Destructive scale
  'bg-destructive-50',
  'bg-destructive-100',
  'bg-destructive-500',
  'bg-destructive-600',
  'text-destructive-500',
  'text-destructive-600',
  'text-destructive-700',
  'text-destructive-800',
  'text-destructive-900',
  'border-destructive-200',
  'border-destructive-300',
  'dark:bg-destructive-900',
  'dark:bg-destructive-950',
  'dark:text-destructive-300',
  'dark:text-destructive-400',
  // Success scale
  'bg-success-50',
  'bg-success-100',
  'bg-success-500',
  'bg-success-600',
  'text-success-500',
  'text-success-600',
  'text-success-700',
  'text-success-800',
  'text-success-900',
  'border-success-200',
  'border-success-300',
  'dark:bg-success-900',
  'dark:bg-success-950',
  'dark:text-success-300',
  'dark:text-success-400',
  // Warning scale
  'bg-warning-50',
  'bg-warning-100',
  'bg-warning-500',
  'bg-warning-600',
  'text-warning-500',
  'text-warning-600',
  'text-warning-700',
  'text-warning-800',
  'text-warning-900',
  'border-warning-200',
  'border-warning-300',
  'dark:bg-warning-900',
  'dark:bg-warning-950',
  'dark:text-warning-300',
  'dark:text-warning-400',
  // Info scale
  'bg-info-50',
  'bg-info-100',
  'bg-info-500',
  'bg-info-600',
  'text-info-500',
  'text-info-600',
  'text-info-700',
  'text-info-800',
  'text-info-900',
  'border-info-200',
  'border-info-300',
  'dark:bg-info-900',
  'dark:bg-info-950',
  'dark:text-info-300',
  'dark:text-info-400',
  // Chart colors
  'bg-chart-1',
  'bg-chart-2',
  'bg-chart-3',
  'bg-chart-4',
  'bg-chart-5',
  'text-chart-1',
  'text-chart-2',
  'text-chart-3',
  'text-chart-4',
  'text-chart-5',
  'border-chart-1',
  'border-chart-2',
  'border-chart-3',
  'border-chart-4',
  'border-chart-5',
  // Switch component
  'bg-primary-500',
  'h-5',
  'w-9',
  'h-6',
  'w-11',
  'h-7',
  'w-14',
  'h-4',
  'w-4',
  'w-5',
  'w-6',
  'translate-x-0.5',
  'translate-x-4',
  'translate-x-5',
  'translate-x-7',
  // SchedulePicker / overflow handling
  'overflow-x-auto',
  'overflow-hidden',
  // Select component
  'truncate',
];

export interface MiewebUIPreset {
  darkMode: ['class', '[data-theme="dark"]'];
  safelist: string[];
  theme: {
    extend: Record<string, unknown>;
  };
}

export const miewebUIPreset: MiewebUIPreset = {
  darkMode: ['class', '[data-theme="dark"]'],
  safelist: miewebUISafelist,
  theme: {
    extend: {
      colors: {
        // Primary color scale - easily overridable by consumers
        primary: {
          DEFAULT: 'var(--mieweb-primary, var(--mieweb-primary-500, #27aae1))',
          50: 'var(--mieweb-primary-50, #e6f7fc)',
          100: 'var(--mieweb-primary-100, #b3e6f6)',
          200: 'var(--mieweb-primary-200, #80d5f0)',
          300: 'var(--mieweb-primary-300, #4dc4ea)',
          400: 'var(--mieweb-primary-400, #27aae1)',
          500: 'var(--mieweb-primary-500, #27aae1)',
          600: 'var(--mieweb-primary-600, #1f98ca)',
          700: 'var(--mieweb-primary-700, #1786b3)',
          800: 'var(--mieweb-primary-800, #0f749c)',
          900: 'var(--mieweb-primary-900, #086285)',
          950: 'var(--mieweb-primary-950, #00506e)',
          foreground: 'var(--mieweb-primary-foreground, hsl(210 40% 98%))',
        },
        // Secondary color scale
        secondary: {
          DEFAULT: 'var(--mieweb-secondary-500, #6366f1)',
          50: 'var(--mieweb-secondary-50, #eef2ff)',
          100: 'var(--mieweb-secondary-100, #e0e7ff)',
          200: 'var(--mieweb-secondary-200, #c7d2fe)',
          300: 'var(--mieweb-secondary-300, #a5b4fc)',
          400: 'var(--mieweb-secondary-400, #818cf8)',
          500: 'var(--mieweb-secondary-500, #6366f1)',
          600: 'var(--mieweb-secondary-600, #4f46e5)',
          700: 'var(--mieweb-secondary-700, #4338ca)',
          800: 'var(--mieweb-secondary-800, #3730a3)',
          900: 'var(--mieweb-secondary-900, #312e81)',
          950: 'var(--mieweb-secondary-950, #1e1b4b)',
          foreground: 'var(--mieweb-secondary-foreground, #ffffff)',
        },
        // Neutral / gray scale
        neutral: {
          DEFAULT: 'var(--mieweb-neutral-500, #737373)',
          50: 'var(--mieweb-neutral-50, #fafafa)',
          100: 'var(--mieweb-neutral-100, #f5f5f5)',
          200: 'var(--mieweb-neutral-200, #e5e5e5)',
          300: 'var(--mieweb-neutral-300, #d4d4d4)',
          400: 'var(--mieweb-neutral-400, #a3a3a3)',
          500: 'var(--mieweb-neutral-500, #737373)',
          600: 'var(--mieweb-neutral-600, #525252)',
          700: 'var(--mieweb-neutral-700, #404040)',
          800: 'var(--mieweb-neutral-800, #262626)',
          900: 'var(--mieweb-neutral-900, #171717)',
          950: 'var(--mieweb-neutral-950, #0a0a0a)',
        },
        // Semantic colors using CSS variables for theming
        border: 'var(--mieweb-border, hsl(214.3 31.8% 91.4%))',
        input: 'var(--mieweb-input, hsl(214.3 31.8% 91.4%))',
        ring: 'var(--mieweb-ring, hsl(221.2 83.2% 53.3%))',
        background: 'var(--mieweb-background, hsl(0 0% 100%))',
        foreground: 'var(--mieweb-foreground, hsl(222.2 84% 4.9%))',
        // Component-specific semantic colors
        card: {
          DEFAULT: 'var(--mieweb-card, hsl(0 0% 100%))',
          foreground: 'var(--mieweb-card-foreground, hsl(222.2 84% 4.9%))',
        },
        muted: {
          DEFAULT: 'var(--mieweb-muted, hsl(210 40% 96.1%))',
          foreground: 'var(--mieweb-muted-foreground, hsl(215.4 16.3% 46.9%))',
        },
        // Destructive / error scale
        destructive: {
          DEFAULT: 'var(--mieweb-destructive-500, #ef4444)',
          50: 'var(--mieweb-destructive-50, #fef2f2)',
          100: 'var(--mieweb-destructive-100, #fee2e2)',
          200: 'var(--mieweb-destructive-200, #fecaca)',
          300: 'var(--mieweb-destructive-300, #fca5a5)',
          400: 'var(--mieweb-destructive-400, #f87171)',
          500: 'var(--mieweb-destructive-500, #ef4444)',
          600: 'var(--mieweb-destructive-600, #dc2626)',
          700: 'var(--mieweb-destructive-700, #b91c1c)',
          800: 'var(--mieweb-destructive-800, #991b1b)',
          900: 'var(--mieweb-destructive-900, #7f1d1d)',
          950: 'var(--mieweb-destructive-950, #450a0a)',
          foreground: 'var(--mieweb-destructive-foreground, hsl(210 40% 98%))',
        },
        // Success scale
        success: {
          DEFAULT: 'var(--mieweb-success-500, #22c55e)',
          50: 'var(--mieweb-success-50, #f0fdf4)',
          100: 'var(--mieweb-success-100, #dcfce7)',
          200: 'var(--mieweb-success-200, #bbf7d0)',
          300: 'var(--mieweb-success-300, #86efac)',
          400: 'var(--mieweb-success-400, #4ade80)',
          500: 'var(--mieweb-success-500, #22c55e)',
          600: 'var(--mieweb-success-600, #16a34a)',
          700: 'var(--mieweb-success-700, #15803d)',
          800: 'var(--mieweb-success-800, #166534)',
          900: 'var(--mieweb-success-900, #14532d)',
          950: 'var(--mieweb-success-950, #052e16)',
          foreground: 'var(--mieweb-success-foreground, hsl(355.7 100% 97.3%))',
        },
        // Warning scale
        warning: {
          DEFAULT: 'var(--mieweb-warning-500, #f59e0b)',
          50: 'var(--mieweb-warning-50, #fffbeb)',
          100: 'var(--mieweb-warning-100, #fef3c7)',
          200: 'var(--mieweb-warning-200, #fde68a)',
          300: 'var(--mieweb-warning-300, #fcd34d)',
          400: 'var(--mieweb-warning-400, #fbbf24)',
          500: 'var(--mieweb-warning-500, #f59e0b)',
          600: 'var(--mieweb-warning-600, #d97706)',
          700: 'var(--mieweb-warning-700, #b45309)',
          800: 'var(--mieweb-warning-800, #92400e)',
          900: 'var(--mieweb-warning-900, #78350f)',
          950: 'var(--mieweb-warning-950, #451a03)',
          foreground: 'var(--mieweb-warning-foreground, hsl(26 83.3% 14.1%))',
        },
        // Info scale
        info: {
          DEFAULT: 'var(--mieweb-info-500, #0ea5e9)',
          50: 'var(--mieweb-info-50, #f0f9ff)',
          100: 'var(--mieweb-info-100, #e0f2fe)',
          200: 'var(--mieweb-info-200, #bae6fd)',
          300: 'var(--mieweb-info-300, #7dd3fc)',
          400: 'var(--mieweb-info-400, #38bdf8)',
          500: 'var(--mieweb-info-500, #0ea5e9)',
          600: 'var(--mieweb-info-600, #0284c7)',
          700: 'var(--mieweb-info-700, #0369a1)',
          800: 'var(--mieweb-info-800, #075985)',
          900: 'var(--mieweb-info-900, #0c4a6e)',
          950: 'var(--mieweb-info-950, #082f49)',
          foreground: 'var(--mieweb-info-foreground, #ffffff)',
        },
        // Chart / data visualization
        chart: {
          1: 'var(--mieweb-chart-1, #27aae1)',
          2: 'var(--mieweb-chart-2, #22c55e)',
          3: 'var(--mieweb-chart-3, #f59e0b)',
          4: 'var(--mieweb-chart-4, #ef4444)',
          5: 'var(--mieweb-chart-5, #6366f1)',
        },
      },
      fontFamily: {
        sans: [
          'var(--mieweb-font-sans, ui-sans-serif)',
          'system-ui',
          'sans-serif',
        ],
      },
      borderRadius: {
        '2xl': 'var(--mieweb-radius-2xl, 1rem)',
        lg: 'var(--mieweb-radius-lg, 0.75rem)',
        md: 'var(--mieweb-radius-md, 0.5rem)',
        sm: 'var(--mieweb-radius-sm, 0.25rem)',
        xl: 'var(--mieweb-radius-xl, 1rem)',
      },
      boxShadow: {
        card: 'var(--mieweb-shadow-card, 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1))',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'slide-in-from-top': {
          '0%': { transform: 'translateY(-0.5rem)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-in-from-bottom': {
          '0%': { transform: 'translateY(0.5rem)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-in-right': {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'slide-in-left': {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      animation: {
        'fade-in': 'fade-in 150ms ease-out',
        'fade-out': 'fade-out 150ms ease-in',
        'slide-in-from-top': 'slide-in-from-top 150ms ease-out',
        'slide-in-from-bottom': 'slide-in-from-bottom 150ms ease-out',
        'slide-in-right': 'slide-in-right 300ms ease-out',
        'slide-in-left': 'slide-in-left 300ms ease-out',
        'scale-in': 'scale-in 150ms ease-out',
      },
    },
  },
};

export default miewebUIPreset;
